<a href="https://colab.research.google.com/github/sakeefkarim/soci-269-f25/blob/main/code/week%2010/soci_269_w10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://collegeaim.org/wp-content/uploads/2021/09/Amherst.png" alt="Amherst Logo" width="200"/>

# Cleaning and Data Analysis in `Python` <img src="https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/community/logos/python-logo-only.png" alt="Python logo" width="30">

[Sakeef M. Karim](https://www.sakeefkarim.com/)  
skarim@amherst.edu

## Preliminaries

This notebook is designed to provide a basic introduction to select libraries in `Python` that are *essential* for data science—inclusive of [`pandas`](https://pandas.pydata.org/)  and [`polars`](https://pola.rs/) for data wrangling as well as [`seaborn`](https://seaborn.pydata.org/) for data visualization. More concretely, it will offer some basic code for (i) manipulating tabular data frames;  and (ii) visualizing descriptive statistics. However, this notebook **will not** provide an exhaustive overview of the affordances of `Python` for research in the social and behavioural sciences, nor will it get into the weeds of [`scikit-learn`](https://scikit-learn.org/stable/) or other machine learning libraries that `Python` is known for (fear not: we'll discuss machine learning in a few weeks).

## Loading Libraries

To kick things off, let's load our essential libraries.

In [1]:
# We use canonical naming conventions for our libraries and submodules:

import scipy as sp
import numpy as np
# Our workhorse libraries for data manipulation
import pandas as pd
import polars as pl

# If you're interested in fitting some parametric models ...

import statsmodels.api as sm
from statsmodels.formula.api import ols, logit

# Our main data visualization libraries:

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

# An experimental submodule that brings the "grammar of graphics" into seaborn:

import seaborn.objects as so

# An approximation of ggplot2 for Python:

import plotnine as p9

### Note

If you're using [Google Colab](https://colab.google/), you can "mount" your Google Drive folders onto a Colab session to save plots, data sets and so on. To programmatically mount your Drive folder(s), run the following lines:

In [ ]:
from google.colab import drive
drive.mount('/drive')

# Using `Pandas` for Data Wrangling

## Loading Data

To read in different _kinds_ of input data, we will use methods (i.e., functions) from the `pandas` library. For today's session, we will largely work with a dataset that we've already encountered —
 <a href="https://jennybc.github.io/gapminder/" target="_blank">gapminder</a>.

 ### Note

 If you're using Jupyter _locally_, you will want to:

 1. Clone/download our companion GitHub repository, <a href="https://github.com/sakeefkarim/soci-269-f25" target="_blank">`soci-269-f25`</a>.

 2. _Change your working directory_ (via the command line) so that it points to the `soci-269-f25` folder you just cloned/downloaded.


 To implement Step 2, feel free to un-annotate the code snippet below and run the cell — but please **remember to adjust the code as needed** (i.e., to reflect where `soci-269-f25` is located on your machine).

In [ ]:
# cd "THE PATH TO ... /soci-269-f25"

### Excel and CSV Files

In [2]:
# From the companion GitHub repository:

gapminder = pd.read_csv("https://github.com/sakeefkarim/soci-269-f25/raw/refs/heads/main/data/week%2010/gapminder.csv")

gapminder_xlsx = pd.read_excel("https://github.com/sakeefkarim/soci-269-f25/raw/refs/heads/main/data/week%2010/gapminder.xlsx")

gapminder

# If you have the soci-269-f25 folder on your machine:

# gapminder_excel = pd.read_excel("week 10/data/gapminder.xlsx")

# gapminder_csv = pd.read_csv("week 10/data/gapminder.csv")

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

### Stata Files

In [ ]:
# From the companion GitHub repository:

gapminder_dta = pd.read_stata("https://github.com/sakeefkarim/soci-269-f25/raw/refs/heads/main/data/week%2010/gapminder.dta")

# If you have the soci-269-f25 folder on your machine:

# gapminder_dta = pd.read_stata("week 10/data/gapminder.dta")

In [ ]:
# If you want to read in SPSS files, you may want to launch this notebook locally.

# Then, make sure you have pyreadstat installed within your conda environment — say, by running

# conda install pyreadstat

# In your terminal. You can then run the code below:

# gapminder_spss = pd.read_spss("week 10/data/gapminder.sav")

## Exploring the Data

In [ ]:
#  Let's use the "head" method to get more information

gapminder.head()

?gapminder.head

### Question

How can we look at the first **ten** observations in `gapminder`?

In [ ]:
# What if we want to take a peak at the last few observations in our dataset?

gapminder.tail()

In [ ]:
# Dimensions of our data frame:

gapminder.shape

# List the columns/variables we have at our disposal:

gapminder.columns

# What *type* of variable is "continent"?

print(gapminder['continent'].dtype)

# Let's look at all the "dtypes":

gapminder.dtypes

### Exploratory Visualizations

Here's a very useful way to explore your data via `seaborn`. We'll be returning to `seaborn` next week.

In [ ]:
# This unlocks seaborn's basic 'dark grid' theme:

sns.set_theme()

# Other seaborn themes: http://seaborn.pydata.org/tutorial/aesthetics.html#seaborn-figure-styles

sns.pairplot(gapminder)

# The 'hue' parameter (for most seaborn functions) allows analysts to condition
# on a variable of interest:

sns.pairplot(gapminder, hue = 'continent')

## Descriptive Statistics

In [18]:
# Basic Descriptives

gapminder.describe()

# Include non-numeric variables:

gapminder.describe(include='all')

# ONLY include non-numeric variables:

gapminder.describe(include=['object'])

# Calculate frequency of different continents in data set:

gapminder.continent.value_counts(normalize=True)

continent
Africa     0.37
Asia       0.23
Europe     0.21
Americas   0.18
Oceania    0.01
Name: proportion, dtype: float64

In [23]:
# Getting out of scientific notation—will display two decimal places

pd.set_option('display.float_format', '{:.2f}'.format)

# Zeroing-in on numeric variables:

gapminder.head(50).mean(numeric_only = True)

gapminder.select_dtypes(exclude=['object']).head(50).mean()

gapminder.select_dtypes(include=[np.number]).head(50).mean()

 #We can also store the subsetted dataframe as an object before applying the mean function:

gapminder_50 = gapminder.select_dtypes(exclude=['object']).head(50)

gapminder_50.mean(numeric_only = True)

# Are these statistics informative at all? Hint: they're not! But why?

# We'll produce more informative descriptives below — after we've touched on
# filtering and reshaping.

# And here's how we can calculate the mean of a few variables—

gapminder[["lifeExp", "gdpPercap"]].mean()

lifeExp       59.47
gdpPercap   7215.33
dtype: float64

In [30]:
# Group data by continent:

gapminder_continent = gapminder.groupby('continent')

gapminder_continent.mean(numeric_only = True)

# Grouped averages for life expectancy:

gapminder_continent[['lifeExp']].mean(numeric_only=True)

# Grouped averages for life expectancy (descending):

gapminder_continent[['lifeExp']].mean().sort_values(by = 'lifeExp', ascending=False)

# Grouped averages for life expectancy by continent and year, descending

(
    gapminder
    .groupby(['continent', 'year'],
             # Removes "grouped" index by continent
             as_index=False)
    [['lifeExp']]
    .mean(numeric_only=True)
    .sort_values(['continent', 'lifeExp'], ascending=False)
)

           lifeExp
continent
Africa       48.87
Americas     64.66
Asia         60.06
Europe       71.90
Oceania      74.33

## Filtering Observations, Column Selection

In [ ]:
# Select column — life expectancy:

gapminder['lifeExp']

gapminder.lifeExp

gapminder[['lifeExp']]

# Selecting three columns: country, life expectancy, continent

gapminder[['continent', 'country', 'lifeExp']]

# What *kind* of variables are we dealing with?

gapminder[['continent', 'country', 'lifeExp']].dtypes

In [ ]:
gapminder_select = gapminder.query("lifeExp >= 80" )

# Dimensions (original data frame)

print(gapminder.shape)

# Dimensions (subsetted data frame)

print(gapminder_select.shape)

In [ ]:
gapminder_africa = gapminder.query("continent == 'Africa'")

# gapminder_africa.continent.drop_duplicates()

gapminder_africa.head()

gapminder_africa.reset_index(drop=True).head()

In [32]:
# Subsetting rows based on *index label*:

gapminder.loc[0:10]

# Subsetting rows based on *integer position*:

gapminder.iloc[0:10]

# Subsetting rows based on values of a variable:

gapminder[gapminder['lifeExp'] == gapminder['lifeExp'].min()]

gapminder[
    (gapminder['lifeExp'] == gapminder['lifeExp'].min()) |
    (gapminder['lifeExp'] == gapminder['lifeExp'].max())
]

     country continent  year  lifeExp        pop  gdpPercap
803    Japan      Asia  2007    82.60  127467972   31656.07
1292  Rwanda    Africa  1992    23.60    7290203     737.07

In [22]:
# First row, first column — pursuant to row/column position

gapminder.iloc[0, 0]

# Subset data frame based on labels:

gapminder.loc[0, 'country']

# Produce data frame based on row/column labels:

gapminder.loc[[0], ['country']]

# Produce data frame based on row/column positions:

gapminder.iloc[[0], [0]]

# Last row:

gapminder.iloc[-1]

# Last column:

gapminder.iloc[:, [-1]]

# First and sixth rows + second and fourth columns:

gapminder.iloc[[0, 5], [1, 3]]

gapminder.loc[[0, 5], gapminder.columns[[1, 3]]]

(
    gapminder
    .iloc[:, [1,3]]
    # If you know the column names—
    #.filter(regex="cont|life")
    .loc[[0, 5]]
)

  continent  lifeExp
0      Asia    28.80
5      Asia    38.44

## Cleaning (Recoding, New Variables *etc.*)

In [ ]:
# Let's zero-in on the latest year in the gapminder data set:

gapminder_07 = gapminder.query("year == 2007 and continent != 'Oceania'").reset_index(drop=True)

# The year variable's no longer necessary! Let's drop it:

gapminder_07.drop(columns='year',
                  # The inplace parameter executes the command "quietly" — i.e.,
                  # no output is displayed and the results do not have to be stored in a
                  # new object:
                  inplace = True)

# Let's rename some columns

gapminder_07.rename(columns={# Existing column name : new column name
                   'gdpPercap':'gdp_pc',
                   'lifeExp':'le'}, inplace=True)

# For illustrative purposes, let's generate new variables that take the log of
# per capita GDP/population:

gapminder_07['ln_gdp'] = np.log(gapminder_07['gdp_pc'])

gapminder_07['ln_pop'] = np.log(gapminder_07['pop'])

# Discretizing population size and per capita GDP into new quintile measures:

gapminder_07['pop_quintile'] = pd.qcut(gapminder_07['pop'], q = 5, labels=False) + 1

gapminder_07['gdp_quintile'] = pd.qcut(gapminder_07['gdp_pc'], q = 5, labels=False) + 1

# Using quintile measures to create crude binary indicators

gapminder_07['size'] = np.where(gapminder_07['pop_quintile'] > 4, 'Large', 'Small or Medium')

# gapminder_07['size'] = gapminder_07['size'].map({'Large': 1, 'Small or Medium': 0})

gapminder_07['wealth'] = np.where(gapminder_07['gdp_quintile'] > 3, 'Top 2 Quintiles', 'Bottom 3 Quintiles')

gapminder_07.filter(like="quint").dtypes

# Transforming quintile measures into categorical variables

gapminder_07[['pop_quintile', 'gdp_quintile']] = gapminder_07.filter(like="quint").astype('category')

# Exercises

### Work With the `penguins` Data Frame


Now, it's your turn to wrangle (or "pre-process") data in `Python`. To do so, you'll be working with *another* dataset you've encountered before— i.e., the `penguins` data frame from the wonderful [`{palmerpenguins}`](https://allisonhorst.github.io/palmerpenguins/) package.

You can access different versions of `penguins` via <a href="https://github.com/sakeefkarim/soci-269-f25/tree/main/data/week%2010" target="_blank">`soci-269-f25/data/week 10`</a>. For those of you who are new to `Python`, feel free to download some helpful cheat sheets from <a href="https://github.com/sakeefkarim/soci-269-f25/tree/main/misc/python%20cheat%20sheets" target="_blank">`soci-269-f25/misc/python cheat sheets`</a>.


### Tasks

1. Load `penguins` into your `Jupyter Notebook`.

2. What are the *dimensions* of the `penguins` data frame (e.g., rows and columns)?

3. List all the columns in `penguins` and what *kinds* of variables they are.

4. Show the first 10 rows in the dataset.

5. Show the last 20 rows in the dataset.

6. Visualize the bivariate relationships between all numeric variables in `penguins` — but make sure these visual summaries vary by the `species` variable.

7. Generate basic descriptive statistics for all numeric variables.

8. Generate basic descriptive statistics for all discrete variables.

9. Isolate the first 35 observations in `penguins` and display the mean values associated with *all numeric variables* (for these 35 observations).

10. Show the mean value for `bill_length_mm` at different levels of `species` (more concretely, produce grouped averages for different penguins species). Sort the rows by descending (mean) values of `bill_length_mm`.

11. Create a new data frame that:

  + Only includes data from the latest `year` in `penguins`.
  + Resets the index value for each observation.
  + Removes the `year` variable.

12. Show the rows corresponding to index values of `0` and `21` in your new data frame.

13. Show the 10<sup>th</sup> and 20<sup>th</sup> observation in your new data frame.

14. Rename at least two of the variables in your new data frame; store the results.

15. Using your custom data frame, generate new numeric and discrete variables; once again, store the results.